### ISSUE TITLE
Friendly reminder to add support for innerWrappingDivStyle prop

### ISSUE THREAD

**Issue by darcyadams** [jcoreio/react-router-drilldown#3]
you were kind enough to add this prop to `react-view-slider`, hoping `react-router-drilldown` can pass support it as well.

**Comment by jedwards1211** [comment]
heh flow failed in the CI build, wish I could make it automatically restart when that happens

**Comment by jedwards1211** [comment]
Okay done :)

:tada: This fix is included in version 5.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-router-drilldown)
- [GitHub release](https://github.com/jcoreio/react-router-drilldown/releases/tag/v5.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by darcyadams** [comment]
very thankful, your help is much appreciated. I was ready for this issue to be open for weeks.

**Comment by jedwards1211** [comment]
glad I could help!  Now if only helping manage `flow-runtime` were this easy hahaha

**Comment by darcyadams** [comment]
one other question for you, how come your don't add `react-transition-context` as a non-dev dependency? do you expect users of this to already have it installed?

**Comment by jedwards1211** [comment]
oh good catch!  I used to have it as a peerDependency, but now I intended to make it a full dependency, let me fix that

**Comment by jedwards1211** [comment]
okay that fix to `react-view-slider` just got released, if you use `react-fader` the same fix is on its way there as well

**Comment by darcyadams** [comment]
FYI, your libs in action, and scrolling works!...
[drilldown.mov.zip](https://github.com/jcoreio/react-router-drilldown/files/3154235/drilldown.mov.zip)

(sorry for the zip, GH did like my mov file)

**Comment by jedwards1211** [comment]
cool, looks nice!

**Comment by jedwards1211** [comment]
btw I haven't added a note in the docs here about https://github.com/jcoreio/react-transition-context#useautofocusref-hook yet, but you may want to use that to autofocus your search inputs after the drilldown transition finishes

**Comment by jedwards1211** [comment]
er, nevermind, autofocus would be annoying there since it's a mobile app :) but on desktop it's nice

**Comment by darcyadams** [comment]
thanks for the tip!
